[tools]
rojo = { source = "rojo-rbx/rojo", version = "7.0.0" }
run-in-roblox = { source = "rojo-rbx/run-in-roblox", version = "0.3" }
selene = { source = "Kampfkarren/selene", version = "0.15" }
stylua = { source = "JohnnyMorganz/stylua", version = "0.11.3" }
